import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AccountCard } from '@/components/AccountCard';
import { INTERVALS, useReminders, type IntervalKey } from '@/context/ReminderContext';
import { useColors } from '@/hooks/useColors';
import { useLanguage } from '@/context/LanguageContext';

function formatDate(value: string) { return new Intl.DateTimeFormat('ar', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value)); }
export default function AccountDetailScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const { accounts, markPasswordChanged, removeAccount, updateAccount } = useReminders(); const { language, isRTL, t, intervalLabel } = useLanguage();
  const account = accounts.find((item) => item.id === id); const [editing, setEditing] = useState(false); const [interval, setInterval] = useState<IntervalKey>(account?.intervalKey ?? 'month');
  if (!account) return <View style={[styles.center, { backgroundColor: colors.background }]}><Text style={{ color: colors.foreground }}>{t('accountMissing')}</Text></View>;
  const currentAccount = account;
  async function changed() { await markPasswordChanged(currentAccount.id); Alert.alert(t('great'), t('reminderUpdated')); }
  async function saveInterval() { await updateAccount(currentAccount.id, currentAccount.serviceName, interval); setEditing(false); }
  function confirmDelete() { Alert.alert(t('deleteAccount'), t('deleteAccountBody'), [{ text: t('cancel'), style: 'cancel' }, { text: t('delete'), style: 'destructive', onPress: async () => { await removeAccount(currentAccount.id); router.back(); } }]); }
  const locale = language === 'ar' ? 'ar' : 'en';
  const dateLabel = (value: string) => new Intl.DateTimeFormat(locale, { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value));
  return <View style={[styles.screen, { backgroundColor: colors.background, direction: isRTL ? 'rtl' : 'ltr' }]}><View style={[styles.top, { paddingTop: insets.top + 12 }]}><Pressable onPress={() => router.back()} hitSlop={12}><Feather name="arrow-right" size={23} color={colors.foreground} /></Pressable><Text style={[styles.topTitle, { color: colors.foreground }]}>{t('accountDetails')}</Text><Pressable onPress={confirmDelete} hitSlop={12}><Feather name="trash-2" size={20} color={colors.destructive} /></Pressable></View><View style={{ padding: 20 }}><AccountCard account={account} onPress={() => undefined} /><View style={[styles.status, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.statusTitle, { color: colors.foreground }]}>{t('reminderStatus')}</Text><View style={styles.infoRow}><Text style={[styles.infoValue, { color: colors.foreground }]}>{dateLabel(account.lastChangedAt)}</Text><Text style={[styles.infoLabel, { color: colors.mutedForeground }]}>{t('lastChange')}</Text></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View style={styles.infoRow}><Text style={[styles.infoValue, { color: colors.mintStrong }]}>{dateLabel(account.nextReminderAt)}</Text><Text style={[styles.infoLabel, { color: colors.mutedForeground }]}>{t('nextReminderDate')}</Text></View></View>
    <Pressable testID="password-changed-button" onPress={changed} style={({ pressed }) => [styles.primary, { backgroundColor: colors.coral, opacity: pressed ? 0.8 : 1 }]}><Feather name="check-circle" size={19} color={colors.primaryForeground} /><Text style={styles.primaryText}>{t('passwordChanged')}</Text></Pressable>
    <Pressable testID="suggest-password-button" onPress={() => router.push({ pathname: '/generator', params: { service: account.serviceName } })} style={({ pressed }) => [styles.secondaryAction, { backgroundColor: colors.mint, opacity: pressed ? 0.75 : 1 }]}><Feather name="key" size={18} color={colors.mintStrong} /><Text style={[styles.secondaryText, { color: colors.mintStrong }]}>{t('passwordSuggestion')}</Text></Pressable>
    <View style={[styles.editBox, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.editHeader}><Text style={[styles.editTitle, { color: colors.foreground }]}>{t('reminderFrequency')}</Text><Pressable onPress={() => editing ? saveInterval() : setEditing(true)}><Text style={[styles.editAction, { color: colors.coral }]}>{editing ? t('save') : t('edit')}</Text></Pressable></View>{editing ? <View style={styles.grid}>{INTERVALS.map((item) => <Pressable key={item.key} onPress={() => setInterval(item.key)} style={[styles.choice, { backgroundColor: interval === item.key ? colors.navy : colors.background, borderColor: interval === item.key ? colors.navy : colors.border }]}><Text style={[styles.choiceText, { color: interval === item.key ? '#FFFFFF' : colors.foreground }]}>{intervalLabel(item.key)}</Text>{interval === item.key ? <Feather name="check" size={14} color={colors.coral} /> : null}</Pressable>)}</View> : <Text style={[styles.intervalValue, { color: colors.mutedForeground }]}>{intervalLabel(account.intervalKey)}</Text>}</View>
  </View></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, top: { paddingHorizontal: 20, paddingBottom: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, topTitle: { fontSize: 17, fontWeight: '700' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, status: { marginTop: 17, borderRadius: 22, borderWidth: 1, padding: 18 }, statusTitle: { fontSize: 16, fontWeight: '700', textAlign: 'right', marginBottom: 15 }, infoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, infoLabel: { fontSize: 13 }, infoValue: { fontSize: 14, fontWeight: '600' }, divider: { height: 1, marginVertical: 15 }, primary: { minHeight: 55, borderRadius: 18, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 9, marginTop: 15 }, primaryText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' }, secondaryAction: { minHeight: 50, borderRadius: 17, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 9, marginTop: 10 }, secondaryText: { fontSize: 14, fontWeight: '700' }, editBox: { marginTop: 14, borderRadius: 22, borderWidth: 1, padding: 17 }, editHeader: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, editTitle: { fontSize: 15, fontWeight: '700' }, editAction: { fontSize: 13, fontWeight: '700' }, intervalValue: { textAlign: 'right', fontSize: 14, marginTop: 12 }, grid: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8, marginTop: 15 }, choice: { width: '47%', minHeight: 44, borderRadius: 13, borderWidth: 1, paddingHorizontal: 10, flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, choiceText: { fontSize: 12, fontWeight: '600' } });
