import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { INTERVALS, useReminders, type IntervalKey } from '@/context/ReminderContext';
import { useColors } from '@/hooks/useColors';
import { useLanguage } from '@/context/LanguageContext';

export default function AddScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { addAccount } = useReminders(); const { isRTL, t, intervalLabel } = useLanguage();
  const [serviceName, setServiceName] = useState(''); const [interval, setInterval] = useState<IntervalKey>('month'); const [saving, setSaving] = useState(false);
  async function save() { if (!serviceName.trim()) { Alert.alert(t('requiredName'), t('requiredNameBody')); return; } setSaving(true); try { await addAccount(serviceName, interval); router.back(); } catch { Alert.alert(t('unableToSave'), t('unableToSaveBody')); } finally { setSaving(false); } }
  return <View style={[styles.screen, { backgroundColor: colors.background, direction: isRTL ? 'rtl' : 'ltr' }]}><View style={[styles.top, { paddingTop: insets.top + 12 }]}><Pressable onPress={() => router.back()} hitSlop={12}><Feather name="arrow-right" size={23} color={colors.foreground} /></Pressable><Text style={[styles.topTitle, { color: colors.foreground }]}>{t('addAccount')}</Text><View style={{ width: 23 }} /></View><KeyboardAwareScrollViewCompat contentContainerStyle={{ padding: 20, paddingBottom: insets.bottom + 28 }} showsVerticalScrollIndicator={false}>
    <Text style={[styles.title, { color: colors.foreground }]}>{t('addAccountTitle')}</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>{t('addAccountBody')}</Text>
    <Text style={[styles.label, { color: colors.foreground }]}>{t('accountName')}</Text><View style={[styles.inputWrap, { backgroundColor: colors.card, borderColor: serviceName ? colors.coral : colors.border }]}><Feather name="at-sign" size={18} color={colors.mutedForeground} /><TextInput testID="service-name-input" value={serviceName} onChangeText={setServiceName} placeholder={t('accountPlaceholder')} placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} autoCapitalize="words" textAlign={isRTL ? 'right' : 'left'} /></View>
    <View style={styles.labelRow}><Text style={[styles.label, { color: colors.foreground }]}>{t('reminderFrequency')}</Text><Text style={[styles.helper, { color: colors.mutedForeground }]}>{t('chooseFrequency')}</Text></View><View style={styles.grid}>{INTERVALS.map((item) => <Pressable testID={'interval-' + item.key} key={item.key} onPress={() => setInterval(item.key)} style={({ pressed }) => [styles.choice, { backgroundColor: interval === item.key ? colors.navy : colors.card, borderColor: interval === item.key ? colors.navy : colors.border, opacity: pressed ? 0.75 : 1 }]}><Text style={[styles.choiceText, { color: interval === item.key ? '#FFFFFF' : colors.foreground }]}>{intervalLabel(item.key)}</Text>{interval === item.key ? <Feather name="check" size={15} color={colors.coral} /> : null}</Pressable>)}</View>
    <View style={[styles.privacy, { backgroundColor: colors.mint }]}><Feather name="lock" size={17} color={colors.mintStrong} /><Text style={[styles.privacyText, { color: colors.mintStrong }]}>{t('localPrivacy')}</Text></View>
    <Pressable testID="save-account-button" disabled={saving} onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: colors.coral, opacity: saving ? 0.5 : pressed ? 0.8 : 1 }]}><Text style={styles.saveText}>{saving ? t('saving') : t('saveReminder')}</Text><Feather name="arrow-left" size={18} color={colors.primaryForeground} /></Pressable>
  </KeyboardAwareScrollViewCompat></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, top: { paddingHorizontal: 20, paddingBottom: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, topTitle: { fontSize: 17, fontWeight: '700' }, title: { fontSize: 27, fontWeight: '700', lineHeight: 35, textAlign: 'right', marginTop: 12 }, subtitle: { fontSize: 14, lineHeight: 22, textAlign: 'right', marginTop: 9, marginBottom: 27 }, label: { fontSize: 14, fontWeight: '700', textAlign: 'right', marginBottom: 9 }, inputWrap: { height: 56, borderWidth: 1, borderRadius: 17, flexDirection: 'row-reverse', alignItems: 'center', gap: 10, paddingHorizontal: 16, marginBottom: 25 }, input: { flex: 1, fontSize: 15 }, labelRow: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, helper: { fontSize: 12 }, grid: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 9, marginTop: 4, marginBottom: 24 }, choice: { width: '47%', minHeight: 48, borderRadius: 15, borderWidth: 1, paddingHorizontal: 12, flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, choiceText: { fontSize: 13, fontWeight: '600' }, privacy: { padding: 15, borderRadius: 17, flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 10, marginBottom: 24 }, privacyText: { flex: 1, fontSize: 12, lineHeight: 19, textAlign: 'right' }, save: { minHeight: 56, borderRadius: 18, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 10 }, saveText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' } });
