import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AccountCard } from '@/components/AccountCard';
import { BrandMark } from '@/components/BrandMark';
import { useReminders } from '@/context/ReminderContext';
import { useColors } from '@/hooks/useColors';
import { useLanguage } from '@/context/LanguageContext';

export default function HomeScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { accounts, loading, removeAccount } = useReminders();
  const { language, isRTL, t } = useLanguage();
  const nextAccount = useMemo(() => accounts.slice().sort((a, b) => new Date(a.nextReminderAt).getTime() - new Date(b.nextReminderAt).getTime())[0], [accounts]);
  function confirmDelete(id: string, serviceName: string) {
    Alert.alert(t('deleteAccount'), t('deleteAccountBody'), [
      { text: t('cancel'), style: 'cancel' },
      { text: t('delete'), style: 'destructive', onPress: () => removeAccount(id) },
    ]);
  }
  if (loading) return <View style={[styles.loading, { backgroundColor: colors.background }]}><BrandMark /><Text style={[styles.loadingText, { color: colors.mutedForeground }]}>{t('loading')}</Text></View>;
  return <View style={[styles.screen, { backgroundColor: colors.background, direction: isRTL ? 'rtl' : 'ltr' }]}>
    <FlatList data={accounts} keyExtractor={(item) => item.id} scrollEnabled={accounts.length > 0} showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingTop: insets.top + 20, paddingBottom: insets.bottom + 30, paddingHorizontal: 20, gap: 12 }} renderItem={({ item }) => <AccountCard account={item} onPress={() => router.push({ pathname: '/account/[id]', params: { id: item.id } })} onDelete={() => confirmDelete(item.id, item.serviceName)} />} ListHeaderComponent={<>
      <View style={styles.header}><View style={styles.headerActions}><Pressable testID="generator-button" onPress={() => router.push('/generator')} hitSlop={12} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.card, opacity: pressed ? 0.65 : 1 }]}><Feather name="key" size={19} color={colors.foreground} /></Pressable><Pressable testID="settings-button" onPress={() => router.push('/settings')} hitSlop={12} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.card, opacity: pressed ? 0.65 : 1 }]}><Feather name="sliders" size={19} color={colors.foreground} /></Pressable><BrandMark small /></View><View style={styles.headerText}><Text style={[styles.eyebrow, { color: colors.coral }]}>{t('safeSpace')}</Text><Text style={[styles.title, { color: colors.foreground }]}>{t('welcome')}</Text></View></View>
      <View style={[styles.hero, { backgroundColor: colors.navy }]}><View style={styles.heroText}><Text style={styles.heroEyebrow}>{t('smallHabit')}</Text><Text style={styles.heroTitle}>{t('doNotWait')}</Text><Text style={styles.heroBody}>{t('reminderIntro')}</Text></View><View style={[styles.heroIcon, { backgroundColor: colors.coral }]}><Feather name="shield" size={27} color={colors.primaryForeground} /></View></View>
      <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{t('accounts')}</Text><Text style={[styles.count, { color: colors.mutedForeground }]}>{accounts.length} {accounts.length === 1 ? t('account') : t('accountsPlural')}</Text></View>
      {nextAccount ? <Pressable onPress={() => router.push({ pathname: '/account/[id]', params: { id: nextAccount.id } })} style={[styles.next, { backgroundColor: colors.yellow }]}><View style={[styles.nextIcon, { backgroundColor: colors.yellowStrong }]}><Feather name="bell" size={16} color={colors.primaryForeground} /></View><View style={styles.nextCopy}><Text style={[styles.nextLabel, { color: colors.yellowStrong }]}>{t('nextReminder')}</Text><Text style={[styles.nextName, { color: colors.foreground }]}>{nextAccount.serviceName} · {new Intl.DateTimeFormat(language === 'ar' ? 'ar' : 'en', { day: 'numeric', month: 'long' }).format(new Date(nextAccount.nextReminderAt))}</Text></View><Feather name="arrow-up-left" size={18} color={colors.yellowStrong} /></Pressable> : null}
    </>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.emptyIcon, { backgroundColor: colors.mint }]}><Feather name="check-circle" size={26} color={colors.mintStrong} /></View><Text style={[styles.emptyTitle, { color: colors.foreground }]}>{t('startWithOne')}</Text><Text style={[styles.emptyBody, { color: colors.mutedForeground }]}>{t('emptyBody')}</Text></View>} ListFooterComponent={<Pressable testID="add-account-button" onPress={() => router.push('/add')} style={({ pressed }) => [styles.addButton, { backgroundColor: colors.coral, opacity: pressed ? 0.8 : 1 }]}><Feather name="plus" size={20} color={colors.primaryForeground} /><Text style={styles.addText}>{t('addAccount')}</Text></Pressable>} />
   </View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14 }, loadingText: { fontSize: 14 }, header: { minHeight: 66, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 }, headerActions: { flexDirection: 'row', alignItems: 'center', gap: 10 }, headerText: { alignItems: 'flex-end' }, eyebrow: { fontSize: 12, fontWeight: '700', marginBottom: 5 }, title: { fontSize: 28, fontWeight: '700' }, iconButton: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, hero: { minHeight: 154, borderRadius: 26, padding: 20, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', marginBottom: 25, overflow: 'hidden' }, heroText: { flex: 1, alignItems: 'flex-end', gap: 7 }, heroEyebrow: { color: '#B7C3D7', fontSize: 12, fontWeight: '600' }, heroTitle: { color: '#FFFFFF', fontSize: 24, fontWeight: '700' }, heroBody: { color: '#DCE4F0', fontSize: 13, lineHeight: 20, textAlign: 'right' }, heroIcon: { width: 58, height: 58, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginLeft: 17 }, sectionHeader: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', marginBottom: 7 }, sectionTitle: { fontSize: 19, fontWeight: '700' }, count: { fontSize: 13 }, next: { borderRadius: 17, padding: 12, flexDirection: 'row-reverse', alignItems: 'center', gap: 10, marginBottom: 7 }, nextIcon: { width: 32, height: 32, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, nextCopy: { flex: 1, alignItems: 'flex-end', gap: 2 }, nextLabel: { fontSize: 11, fontWeight: '700' }, nextName: { fontSize: 13, fontWeight: '600' }, empty: { borderWidth: 1, borderRadius: 22, padding: 25, alignItems: 'center', gap: 9, marginTop: 4 }, emptyIcon: { width: 55, height: 55, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 3 }, emptyTitle: { fontSize: 17, fontWeight: '700' }, emptyBody: { textAlign: 'center', fontSize: 13, lineHeight: 20, maxWidth: 270 }, addButton: { minHeight: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', flexDirection: 'row-reverse', gap: 9, marginTop: 7 }, addText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' } });
